Hfs/584 gateway implementation transactions targetid
LBHackney-IT/financial-transactions-api pull request #97
Opened 2022-10-13 10:20 UTC by ilko-adamov

## Link to JIRA ticket

Add a link to the JIRA ticket that the changes in this PR describe.

## Describe this PR

### *What is the problem we're trying to solve*

Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.

### *What changes have we introduced*

Add descriptions of what changes were made to address the problem and provide a solution.

Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.

#### _Checklist_

- [ ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [ ] Added tests to cover all new production code
- [ ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [ ] Checked all code for possible refactoring
- [ ] Code pipeline builds correctly

### *Follow up actions after merging PR*

Are there any next steps that need to addressed after merging this PR? Add them here.

2022-10-13 13:53 UTC, FaisalHackney commented
Hi Ilko, have there been any changes to the unit tests? I would have thought that unit tests need to be amended for this change.
I have not seen how the connection to the Environment database is done - where is the connection opened to the PostgresSQL database on the development environment. And this requires the yml file to be amended with the new database connection settings so that this can be done in circleCI. Please confer with Liudvikas on this point.

Also, there needs to be Integration tests for the local testing. So a docker container with the postgresSQL instance created.

2022-10-24 13:40 UTC, ilko-adamov commented
> Hi Ilko, have there been any changes to the unit tests? I would have thought that unit tests need to be amended for this change. I have not seen how the connection to the Environment database is done - where is the connection opened to the PostgresSQL database on the development environment. And this requires the yml file to be amended with the new database connection settings so that this can be done in circleCI. Please confer with Liudvikas on this point.
> 
> Also, there needs to be Integration tests for the local testing. So a docker container with the postgresSQL instance created.

Done

2022-10-25 08:31 UTC, FaisalHackney requested changes

2022-10-25 08:31 UTC, FaisalHackney commented on FinancialTransactionsApi/V1/Gateways/PostgreDbGateway.cs
> +using Amazon.DynamoDBv2.Model;
remove usings for DynamoDb

2022-10-25 08:31 UTC, FaisalHackney commented on FinancialTransactionsApi/V1/Gateways/PostgreDbGateway.cs
> +        public async Task<List<Transaction>> GetByTargetId(Guid targetId)
Please change this method signature to: `public Task<IEnumerable<Transaction>> GetByTargetId(Guid targetId);`
in the `ITransactionGateway` interface

In fact all methods with `List<T>` should be replaced by `IEnumerable<T>` going forward, please

2022-10-25 08:31 UTC, FaisalHackney commented on FinancialTransactionsApi/V1/Gateways/PostgreDbGateway.cs
> +            var response = await _databaseContext.TransactionEntities.Where(x => x.TargetId == targetId).ToListAsync().ConfigureAwait(false);
Should this not be `_databaseContext.Transactions`  - as in the name of the view/table defined in the `TransactionEntity` data annotation?

2022-10-25 08:31 UTC, FaisalHackney commented on FinancialTransactionsApi/V1/Domain/Transaction.cs
>          [AllowNull]
As per the meeting we had this morning, I think we are removing these fields entirely

2022-10-25 08:31 UTC, FaisalHackney commented on FinancialTransactionsApi/V1/Domain/Transaction.cs
> +    public class Transaction : TransactionBase
I am not sure about this inheritance as all the properties required are in TransctionBase abstract class and the derived Transaction class contains properties that are not needed. Please check with Felipe

2022-10-25 08:31 UTC, FaisalHackney commented on FinancialTransactionsApi/V1/Factories/TransactionFactory.cs
> +        public static List<Transaction> ToDomain(this IEnumerable<TransactionEntity> databaseEntity)
This should return an IEnumerable<T> rather than List<T>

There should be a check for the following:
If the `IEnumerable<TransactionEntity> databaseEntity` is null, the ToDomain() extension method overload should return an empty enumeration of type `Transaction`: `Enumerable.Empty<Transaction>`

Then in the Controller, we can get rid of the horrible null check
```
if (transactions == null || transactions.Count == 0)
                return NotFound(targetId);
```

The controller needs some work, which should be included in this PR

2022-10-25 08:31 UTC, FaisalHackney commented on FinancialTransactionsApi/V1/Factories/TransactionFactory.cs
> +            return entity == null ? null : new Transaction
This should return a nullable Transaction object if the TransactionEntity is null instead of null?
Then upstream, in the UseCase class - you would Convert the Domain class of Transaction to a collection of TransactionResponse.

At the moment there is an error in the Controller, because it is returning the domain object collection - which needs to be corrected!

2022-10-25 08:31 UTC, FaisalHackney commented on database/schema.sql
> +CREATE TABLE IF NOT EXISTS housingfinance_dbo.transactions
This should be the whole SQL Schema of the Postgres database and this should be a View - as it is in the actual database

2022-10-25 08:31 UTC, FaisalHackney commented on FinancialTransactionsApi/V1/Controllers/FinancialTransactionsApiController.cs
> +        public async Task<IActionResult> GetByTargetId([FromRoute] string targetType, [FromRoute] Guid targetId)
Should there be any checks here for invalid/empty targetType and targetId parameters. 
At the very least you should return a BadRequest for an empty or non-Guid targetId and targetType must be non-empty

2022-10-25 08:31 UTC, FaisalHackney commented on FinancialTransactionsApi.Tests/V1/E2ETests/Stories/DynamoDbTransactionIntegrationTest.cs
>              return entity;
This file should be deleted and replaced (or this one renamed)  - PostgresTransactionIntegrationTest.cs

2022-10-25 08:31 UTC, FaisalHackney commented on FinancialTransactionsApi/V1/Infrastructure/Entities/TransactionDbEntity.cs
> +        [NotMapped]
Is this still being used for the Postgres implementation?
Why are there `DynamoDBProperty` attributes still in use here?

2022-10-25 08:31 UTC, FaisalHackney commented on FinancialTransactionsApi/V1/UseCase/GetByTargetIdUseCase.cs
> +        public async Task<ResponseWrapper<IEnumerable<TransactionResponse>>> ExecuteAsync(string targetType, Guid targetId)
nice!

2022-10-25 08:31 UTC, FaisalHackney commented on FinancialTransactionsApi.Tests/AwsIntegrationTests.cs
> +        private const string TestToken = " Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMTUxNjQ3NDY2MzU4MTYwNTkxODQiLCJlbWFpbCI6ImdhYnJpZWxhLm1hcnRpbmlAaGFja25leS5nb3YudWsiLCJpc3MiOiJIYWNr
Can you change this to a string which is not recognisable as a Token. Otherwise Git Guardian checks will flag this as a security leak!!!

2022-10-25 08:58 UTC, ilko-adamov commented on FinancialTransactionsApi/V1/Domain/Transaction.cs
> +    public class Transaction : TransactionBase
Done

2022-10-25 08:58 UTC, ilko-adamov commented on FinancialTransactionsApi/V1/Domain/Transaction.cs
>          [AllowNull]
Done

2022-10-25 08:58 UTC, ilko-adamov commented on FinancialTransactionsApi/V1/Factories/TransactionFactory.cs
> +            return entity == null ? null : new Transaction
Done

2022-10-25 08:59 UTC, ilko-adamov commented on FinancialTransactionsApi/V1/Infrastructure/Entities/TransactionDbEntity.cs
> +        [NotMapped]
Done

2022-10-25 09:10 UTC, ilko-adamov commented on FinancialTransactionsApi/V1/Gateways/PostgreDbGateway.cs
> +        public async Task<List<Transaction>> GetByTargetId(Guid targetId)
Done

2022-10-25 09:14 UTC, ilko-adamov commented on FinancialTransactionsApi/V1/Gateways/PostgreDbGateway.cs
> +            var response = await _databaseContext.TransactionEntities.Where(x => x.TargetId == targetId).ToListAsync().ConfigureAwait(false);
Done

2022-10-25 09:20 UTC, ilko-adamov commented on FinancialTransactionsApi/V1/Gateways/PostgreDbGateway.cs
> +        public async Task<List<Transaction>> GetByTargetId(Guid targetId)
Done

2022-10-25 09:43 UTC, ilko-adamov commented on FinancialTransactionsApi.Tests/V1/E2ETests/Stories/DynamoDbTransactionIntegrationTest.cs
>              return entity;
Done

2022-10-25 09:48 UTC, ilko-adamov commented on FinancialTransactionsApi/V1/UseCase/GetByTargetIdUseCase.cs
> +        public async Task<ResponseWrapper<IEnumerable<TransactionResponse>>> ExecuteAsync(string targetType, Guid targetId)
Done

2022-10-25 09:48 UTC, ilko-adamov commented on FinancialTransactionsApi.Tests/AwsIntegrationTests.cs
> +        private const string TestToken = " Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMTUxNjQ3NDY2MzU4MTYwNTkxODQiLCJlbWFpbCI6ImdhYnJpZWxhLm1hcnRpbmlAaGFja25leS5nb3YudWsiLCJpc3MiOiJIYWNr
Done

2022-10-25 10:12 UTC, ilko-adamov commented on FinancialTransactionsApi/V1/Controllers/FinancialTransactionsApiController.cs
> +        public async Task<IActionResult> GetByTargetId([FromRoute] string targetType, [FromRoute] Guid targetId)
Done

2022-10-25 10:19 UTC, ilko-adamov commented on FinancialTransactionsApi/V1/Factories/TransactionFactory.cs
> +        public static List<Transaction> ToDomain(this IEnumerable<TransactionEntity> databaseEntity)
Done

2022-10-25 10:20 UTC, ilko-adamov commented on database/schema.sql
> +CREATE TABLE IF NOT EXISTS housingfinance_dbo.transactions
Done

2022-10-25 10:21 UTC, ilko-adamov commented on FinancialTransactionsApi/V1/Gateways/PostgreDbGateway.cs
> +using Amazon.DynamoDBv2.Model;
This is going to remove in the next PR, there is a lot of references

2022-10-25 10:39 UTC, FaisalHackney approved these changes

2022-10-25 13:08 UTC, merged